(() => {
  const DB='iOSDesktopDB', STORE='layoutStore', KEY='icityData', CONTACTS='contactsAppData';
  let state={entries:[],messages:[]},authors=[],view='home',profileFilter='all'; const $=s=>document.querySelector(s);
  const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function openStore(mode='readonly'){return new Promise((ok,no)=>{const r=indexedDB.open(DB);r.onerror=()=>no(r.error);r.onsuccess=()=>{const db=r.result,t=db.transaction(STORE,mode);ok({db,t,store:t.objectStore(STORE)})}})}
  async function read(id){const o=await openStore();return new Promise((ok,no)=>{const r=o.store.get(id);r.onsuccess=()=>{o.db.close();ok(r.result)};r.onerror=()=>{o.db.close();no(r.error)}})}
  async function save(){const o=await openStore('readwrite');o.store.put({id:KEY,entries:state.entries,messages:state.messages});return new Promise((ok,no)=>{o.t.oncomplete=()=>{o.db.close();ok()};o.t.onerror=()=>{o.db.close();no(o.t.error)}})}
  async function load(){const [data,contactsRecord]=await Promise.all([read(KEY),read(CONTACTS)]);state={entries:Array.isArray(data?.entries)?data.entries:[],messages:Array.isArray(data?.messages)?data.messages:[]};const c=contactsRecord?.data||{},users=Array.isArray(c.users)?c.users:[],chars=Array.isArray(c.contacts)?c.contacts:[];authors=[...users.map(x=>({...x,type:'user'})),...chars.map(x=>({...x,type:'character'}))].filter(x=>x?.id&&x.name).map(x=>({id:x.id,type:x.type,name:x.name,avatar:x.avatar||''}))}
  const getAuthor=e=>authors.find(a=>a.id===e.authorId&&a.type===e.authorType)||{name:e.authorName||'未知身份',avatar:e.authorAvatar||'',type:e.authorType||'user'};
  const time=n=>{const s=Math.max(0,Math.floor((Date.now()-n)/1000));return s<60?'刚刚':s<3600?Math.floor(s/60)+' 分钟前':s<86400?Math.floor(s/3600)+' 小时前':new Date(n).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})};
  function avatar(a){return '<div class="icity-avatar">'+(a.avatar?'<img src="'+esc(a.avatar)+'" alt="">':esc(a.name.slice(0,1)))+'</div>'}
  function card(e){const a=getAuthor(e);return '<article class="icity-entry"><div class="icity-entry-head">'+avatar(a)+'<div class="icity-author"><strong>'+esc(a.name)+'</strong><span>@'+esc(a.name)+' · '+(a.type==='user'?'User':'角色')+'</span></div><time class="icity-entry-time">'+time(e.createdAt)+'</time></div>'+(e.title?'<h2 class="icity-entry-title">'+esc(e.title)+'</h2>':'')+'<p class="icity-entry-content">'+esc(e.content)+'</p><div class="icity-entry-foot"><span>☁ 百色市 23°C</span><span>♧</span><span>♡</span><span>▢</span><span>◷ '+time(e.createdAt)+'</span><button class="icity-entry-delete" type="button" data-icity-delete="'+esc(e.id)+'">⋮</button></div></article>'}
  function renderFeeds(){const list=[...state.entries].sort((a,b)=>b.createdAt-a.createdAt);$('#icityHomeFeed').innerHTML=list.map(card).join('')||empty('还没有日记','写下今天的片刻，让它留在 iCity。');$('#icityWorldFeed').innerHTML=list.map(card).join('')||empty('世界还很安静','发布第一篇日记吧。');const pf=profileFilter==='all'?list:list.filter(e=>e.authorType===profileFilter);$('#icityProfileFeed').innerHTML=pf.map(card).join('')||empty('这里还没有日记','切换身份后发布一篇日记。');$('#icityMonthCount').textContent=new Date().getMonth()+1+' 月记录';const first=authors.find(a=>a.type==='user')||authors[0];$('#icityPromptAvatar').textContent=first?.name?.slice(0,1)||'i';$('#icityProfileHead').innerHTML=first?avatar(first)+'<div><strong>'+esc(first.name)+' · 日记</strong><span>@'+esc(first.name)+' · iCity</span></div>':'<div><strong>我的日记</strong><span>先在联系人中创建 User 身份</span></div>'}
  function empty(title,text){return '<div class="icity-empty"><div>✎</div><strong>'+title+'</strong><span>'+text+'</span></div>'}
  function renderMessages(){const notices=[{from:'iCity 市政厅',content:'欢迎加入 iCity，你的专属生活记录。从现在开始，随时随地记录生命中的所思所想。',system:true}];const list=[...notices,...state.messages];$('#icityMessages').innerHTML=list.map(m=>'<div class="icity-message '+(m.from==='user'?'is-user':'')+'"><div class="icity-message-avatar">'+(m.from==='user'?'我':'i')+'</div><div class="icity-bubble">'+esc(m.content)+'</div></div>').join('')}
  function show(next){view=next;document.querySelectorAll('[data-icity-view]').forEach(x=>x.classList.toggle('is-active',x.dataset.icityView===next));document.querySelectorAll('[data-icity-nav]').forEach(x=>x.classList.toggle('is-active',x.dataset.icityNav===next));$('#icityPageTitle').textContent=next==='home'?'icity · 我的日记':next==='world'?'iCity · 世界':next==='profile'?'我的日记':'iCity 市政厅';$('#icityTopbar').querySelector('[data-icity-action=close]').dataset.icityAction=next==='home'?'close':'go-home';if(next==='city')renderMessages()}
  function compose(open){const sheet=$('#icityComposeSheet');sheet.classList.toggle('is-open',open);sheet.setAttribute('aria-hidden',String(!open));if(open){const s=$('#icityAuthorSelect');s.innerHTML=authors.map(a=>'<option value="'+esc(a.type+':'+a.id)+'">'+esc(a.name)+' ('+(a.type==='user'?'User':'角色')+')</option>').join('');$('.icity-publish-button').disabled=!authors.length;$('#icityDiaryTitle').focus()}}
  async function publish(e){e.preventDefault();const [type,...ids]=$('#icityAuthorSelect').value.split(':'),a=authors.find(x=>x.type===type&&x.id===ids.join(':')),content=$('#icityDiaryContent').value.trim();if(!a||!content)return;state.entries.unshift({id:'diary_'+Date.now()+'_'+Math.random().toString(36).slice(2,8),authorId:a.id,authorType:a.type,authorName:a.name,authorAvatar:a.avatar,title:$('#icityDiaryTitle').value.trim(),content,createdAt:Date.now()});await save();e.target.reset();$('#icityCharCount').textContent='0 / 2000';compose(false);renderFeeds()}
  async function open(){try{await load();renderFeeds();show('home');$('#icityAppUI').classList.add('is-open');$('#icityAppUI').setAttribute('aria-hidden','false')}catch(e){console.error('Unable to open iCity',e)}}
  function close(){compose(false);$('#icityAppUI').classList.remove('is-open');$('#icityAppUI').setAttribute('aria-hidden','true')}
  document.addEventListener('DOMContentLoaded',()=>{const root=$('#icityAppUI');root?.addEventListener('click',e=>{const action=e.target.closest('[data-icity-action]')?.dataset.icityAction;if(action==='close')close();if(action==='go-home')show('home');if(action==='open-compose')compose(true);if(action==='close-compose')compose(false);if(action==='open-city')show('city');const id=e.target.closest('[data-icity-delete]')?.dataset.icityDelete;if(id){state.entries=state.entries.filter(x=>x.id!==id);save().then(renderFeeds)}});document.querySelectorAll('[data-icity-nav]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.icityNav)));document.querySelectorAll('[data-icity-world]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-icity-world]').forEach(x=>x.classList.toggle('is-active',x===b))}));document.querySelectorAll('[data-icity-profile-filter]').forEach(b=>b.addEventListener('click',()=>{profileFilter=b.dataset.icityProfileFilter;document.querySelectorAll('[data-icity-profile-filter]').forEach(x=>x.classList.toggle('is-active',x===b));renderFeeds()}));$('#icityComposeForm')?.addEventListener('submit',publish);$('#icityDiaryContent')?.addEventListener('input',e=>$('#icityCharCount').textContent=e.target.value.length+' / 2000');$('#icityMessageForm')?.addEventListener('submit',async e=>{e.preventDefault();const input=$('#icityMessageInput'),content=input.value.trim();if(!content)return;state.messages.push({from:'user',content,createdAt:Date.now()});input.value='';await save();renderMessages()})});window.openICityApp=open;window.closeICityApp=close;
})();
