(() => {
  const DB = 'iOSDesktopDB', STORE = 'layoutStore', DIARIES = 'icityData', CONTACTS = 'contactsAppData';
  let entries = [], authors = [], filter = 'all'; const $ = s => document.querySelector(s);
  const esc = v => String(v || '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function store(mode='readonly'){return new Promise((ok,no)=>{const r=indexedDB.open(DB);r.onerror=()=>no(r.error);r.onsuccess=()=>{const db=r.result,t=db.transaction(STORE,mode);ok({db,t,s:t.objectStore(STORE)})}})}
  async function get(id){const o=await store();return new Promise((ok,no)=>{const r=o.s.get(id);r.onsuccess=()=>{o.db.close();ok(r.result)};r.onerror=()=>{o.db.close();no(r.error)}})}
  async function save(){const o=await store('readwrite');o.s.put({id:DIARIES,entries});return new Promise((ok,no)=>{o.t.oncomplete=()=>{o.db.close();ok()};o.t.onerror=()=>{o.db.close();no(o.t.error)}})}
  async function load(){const [d,record]=await Promise.all([get(DIARIES),get(CONTACTS)]);const c=record?.data||{};entries=Array.isArray(d?.entries)?d.entries:[];const users=Array.isArray(c.users)?c.users:[],chars=Array.isArray(c.contacts)?c.contacts:[];authors=[...users,...chars].filter(x=>x?.id&&x.name).map(x=>({id:x.id,type:users.includes(x)?'user':'character',name:x.name,avatar:x.avatar||''}))}
  function author(e){return authors.find(a=>a.id===e.authorId&&a.type===e.authorType)||{name:e.authorName||'未知身份',avatar:e.authorAvatar||'',type:e.authorType}}
  function time(n){const s=Math.max(0,Math.floor((Date.now()-n)/1000));return s<60?'刚刚':s<3600?Math.floor(s/60)+' 分钟前':s<86400?Math.floor(s/3600)+' 小时前':new Date(n).toLocaleDateString('zh-CN',{month:'short',day:'numeric'})}
  function render(){const list=entries.filter(e=>filter!=='mine'||e.authorType==='user').sort((a,b)=>b.createdAt-a.createdAt);$('#icityFeed').innerHTML=list.map(e=>{const a=author(e),av=a.avatar?'<img src="'+esc(a.avatar)+'" alt="">':esc(a.name.slice(0,1));return '<article class="icity-entry"><div class="icity-entry-head"><div class="icity-avatar">'+av+'</div><div class="icity-author"><strong>'+esc(a.name)+'</strong><span>'+(a.type==='user'?'User':'角色')+'</span></div><time class="icity-entry-time">'+time(e.createdAt)+'</time></div>'+(e.title?'<h2 class="icity-entry-title">'+esc(e.title)+'</h2>':'')+'<p class="icity-entry-content">'+esc(e.content)+'</p><div class="icity-entry-actions"><button class="icity-entry-delete" type="button" data-icity-delete="'+esc(e.id)+'">删除</button></div></article>'}).join('');$('#icityEmpty').hidden=Boolean(list.length)}
  function compose(open){$('#icityComposeSheet').classList.toggle('is-open',open);if(open){const s=$('#icityAuthorSelect');s.innerHTML=authors.map(a=>'<option value="'+esc(a.type+':'+a.id)+'">'+esc(a.name)+' ('+(a.type==='user'?'User':'角色')+')</option>').join('');$('.icity-publish-button').disabled=!authors.length;$('#icityDiaryTitle').focus()}}
  async function open(){try{await load();render();$('#icityAppUI').classList.add('is-open');$('#icityAppUI').setAttribute('aria-hidden','false')}catch(e){console.error('Unable to open iCity',e)}}
  function close(){compose(false);$('#icityAppUI').classList.remove('is-open');$('#icityAppUI').setAttribute('aria-hidden','true')}
  async function publish(e){e.preventDefault();const [type,...rest]=$('#icityAuthorSelect').value.split(':'),a=authors.find(x=>x.type===type&&x.id===rest.join(':')),content=$('#icityDiaryContent').value.trim();if(!a||!content)return;entries.unshift({id:'diary_'+Date.now()+'_'+Math.random().toString(36).slice(2,8),authorId:a.id,authorType:a.type,authorName:a.name,authorAvatar:a.avatar,title:$('#icityDiaryTitle').value.trim(),content,createdAt:Date.now()});await save();e.target.reset();$('#icityCharCount').textContent='0 / 2000';compose(false);render()}
  document.addEventListener('DOMContentLoaded',()=>{$('#icityAppUI')?.addEventListener('click',e=>{const action=e.target.closest('[data-icity-action]')?.dataset.icityAction;if(action==='close')close();if(action==='open-compose')compose(true);if(action==='close-compose')compose(false);const id=e.target.closest('[data-icity-delete]')?.dataset.icityDelete;if(id){entries=entries.filter(x=>x.id!==id);save().then(render)}});document.querySelectorAll('[data-icity-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.icityFilter;document.querySelectorAll('[data-icity-filter]').forEach(x=>x.classList.toggle('is-active',x===b));render()}));$('#icityComposeForm')?.addEventListener('submit',publish);$('#icityDiaryContent')?.addEventListener('input',e=>$('#icityCharCount').textContent=e.target.value.length+' / 2000')});window.openICityApp=open;window.closeICityApp=close;
})();
